#UI GENEREATED WITH QT DESIGNER

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow): 
    
        MainWindow.setObjectName("Coronavirus Stats")
        MainWindow.resize(360, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_input = QtWidgets.QTextEdit(self.centralwidget)
        self.user_input.setGeometry(QtCore.QRect(50, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.user_input.setFont(font)
        self.user_input.setObjectName("user_input")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(230, 70, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.search_btn.setFont(font)
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.infected = QtWidgets.QLabel(self.centralwidget)
        self.infected.setGeometry(QtCore.QRect(160, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(20)
        self.infected.setFont(font)
        self.infected.setObjectName("infected")
        self.recovered = QtWidgets.QLabel(self.centralwidget)
        self.recovered.setGeometry(QtCore.QRect(160, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(20)
        self.recovered.setFont(font)
        self.recovered.setObjectName("recovered")
        self.deaths = QtWidgets.QLabel(self.centralwidget)
        self.deaths.setGeometry(QtCore.QRect(160, 200, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(20)
        self.deaths.setFont(font)
        self.deaths.setObjectName("deaths")
        self.infected_text = QtWidgets.QLabel(self.centralwidget)
        self.infected_text.setGeometry(QtCore.QRect(30, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.infected_text.setFont(font)
        self.infected_text.setObjectName("infected_text")
        self.recovered_text = QtWidgets.QLabel(self.centralwidget)
        self.recovered_text.setGeometry(QtCore.QRect(30, 170, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.recovered_text.setFont(font)
        self.recovered_text.setObjectName("recovered_text")
        self.deaths_text = QtWidgets.QLabel(self.centralwidget)
        self.deaths_text.setGeometry(QtCore.QRect(30, 210, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(12)
        self.deaths_text.setFont(font)
        self.deaths_text.setObjectName("deaths_text")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 231, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 231, 16))
        self.label_6.setObjectName("label_6")
        self.error = QtWidgets.QLabel(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(90, 230, 211, 20))
        self.error.setObjectName("error")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.error.setStyleSheet("color: red;")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        MainWindow.setWindowIcon(QtGui.QIcon('./img/icon.png'))
        MainWindow.setFixedSize(340, 360)

        self.deaths_text.setStyleSheet('color: red;')
        self.recovered_text.setStyleSheet('color: green;')

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Coronavirus Stats", "Coronavirus Stats"))
        self.user_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'Fira Code\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Coronavirus Stats"))
        self.infected.setText(_translate("MainWindow", "0.000.000"))
        self.recovered.setText(_translate("MainWindow", "0.000.000"))
        self.deaths.setText(_translate("MainWindow", "0.000.000"))
        self.infected_text.setText(_translate("MainWindow", "Infected"))
        self.recovered_text.setText(_translate("MainWindow", "Recovered"))
        self.deaths_text.setText(_translate("MainWindow", "Deaths"))
        self.label_3.setText(_translate("MainWindow", "*Search \"world\" for world stats"))
        self.label_6.setText(_translate("MainWindow", "*Search \"country\" for world stats( ex: usa)"))
        self.error.setText(_translate("MainWindow", ""))

